bCreatureDefeat: true
bHunterPrideFollower: true
bKillMove: true
bLethalEssential: false
bNotifyColored: false
bNotifyDefeat: true
bNotifyDestroy: false
bNPCDefeat: true
bNPCRescueReload: true
bPlayerDefeat: true
bStripDrop: false
bTraumaEnabled: true
bTraumaHealth: true
ConsequenceEnabled: true
fExposedChance: 0
fKdHealthThresh: 0.200000003
fLethalNPC: 0
fLethalPlayer: 100
fMidCombatBlackout: 10
fStripChance: 0
fStripDestroy: 5
fTraumaMult: 32
fTraumeBackAttack: 2
iExposed: 2
iFollowerRescue: 1
iHunterPrideKey: -1
iHunterPrideKeyMod: -1
iKdFallbackTimer: 90
iStrips: 1066390941
ProcessingEnabled: true
rNotifyColor: "#FF0000"